version: '3.8'
services:
  frontend:
    build: .
    container_name: front-innovatech
    ports:
      - "8080:8080"
    networks:
      - innovatech-net

networks:
  innovatech-net:
    driver: bridge
