name: CI/CD Frontend Innovatech

# 1. Trigger: El "gatillo" que activa el robot 
on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # Paso A: Descargar el código en la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso B: Configurar credenciales de AWS usando Secrets [cite: 114, 146]
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          [cite_start]aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Crítico intento 3
          aws-region: us-east-1

      # Paso C: Autenticación en el registro de Amazon ECR [cite: 111, 147]
      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Paso D: Construcción y subida de la imagen (Build & Push)
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: 058264495714.dkr.ecr.us-east-1.amazonaws.com/frontend-innovatech # Tu compañera debe crear este nombre en AWS ECR
          IMAGE_TAG: latest
        run: |
          # Construye usando el Dockerfile multi-stage que ya probamos [cite: 91]
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Sube la imagen a la nube de AWS
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
